from __future__ import annotations

from typing import Dict, List

WINDOWS_FONTS: List[str] = [
    "Agency FB",
    "Algerian",
    "AniMe Vision - MB_EN",
    "Arabic Transparent",
    "Arial",
    "Arial Baltic",
    "Arial Black",
    "Arial CE",
    "Arial CYR",
    "Arial Greek",
    "Arial Narrow",
    "Arial Rounded MT Bold",
    "Arial TUR",
    "BadaBoom BB",
    "Bahnschrift",
    "Bahnschrift Condensed",
    "Bahnschrift Light",
    "Bahnschrift Light Condensed",
    "Bahnschrift Light SemiCondensed",
    "Bahnschrift SemiBold",
    "Bahnschrift SemiBold Condensed",
    "Bahnschrift SemiBold SemiConden",
    "Bahnschrift SemiCondensed",
    "Bahnschrift SemiLight",
    "Bahnschrift SemiLight Condensed",
    "Bahnschrift SemiLight SemiConde",
    "Baskerville Old Face",
    "Bauhaus 93",
    "Bell MT",
    "Berlin Sans FB",
    "Berlin Sans FB Demi",
    "Bernard MT Condensed",
    "Blackadder ITC",
    "Bodoni MT",
    "Bodoni MT Black",
    "Bodoni MT Condensed",
    "Bodoni MT Poster Compressed",
    "Book Antiqua",
    "Bookman Old Style",
    "Bookshelf Symbol 7",
    "Bradley Hand ITC",
    "Britannic Bold",
    "Broadway",
    "Brush Script MT",
    "Calibri",
    "Calibri Light",
    "Californian FB",
    "Calisto MT",
    "Cambria",
    "Cambria Math",
    "Candara",
    "Candara Light",
    "Cascadia Code",
    "Cascadia Code ExtraLight",
    "Cascadia Code Light",
    "Cascadia Code SemiBold",
    "Cascadia Code SemiLight",
    "Cascadia Mono",
    "Cascadia Mono ExtraLight",
    "Cascadia Mono Light",
    "Cascadia Mono SemiBold",
    "Cascadia Mono SemiLight",
    "Castellar",
    "Centaur",
    "Century",
    "Century Gothic",
    "Century Schoolbook",
    "Chiller",
    "Colonna MT",
    "Comic Sans MS",
    "Consolas",
    "Constantia",
    "Cooper Black",
    "Copperplate Gothic Bold",
    "Copperplate Gothic Light",
    "Corbel",
    "Corbel Light",
    "Courier",
    "Courier New",
    "Courier New Baltic",
    "Courier New CE",
    "Courier New CYR",
    "Courier New Greek",
    "Courier New TUR",
    "Curlz MT",
    "DIN Alternate",
    "DIN Condensed",
    "Dubai",
    "Dubai Light",
    "Dubai Medium",
    "Ebrima",
    "Edwardian Script ITC",
    "Elephant",
    "Engravers MT",
    "Eras Bold ITC",
    "Eras Demi ITC",
    "Eras Light ITC",
    "Eras Medium ITC",
    "Felix Titling",
    "Fixedsys",
    "Footlight MT Light",
    "Forte",
    "Franklin Gothic Book",
    "Franklin Gothic Demi",
    "Franklin Gothic Demi Cond",
    "Franklin Gothic Heavy",
    "Franklin Gothic Medium",
    "Franklin Gothic Medium Cond",
    "Freestyle Script",
    "French Script MT",
    "Gabriola",
    "Gadugi",
    "Garamond",
    "Georgia",
    "Gigi",
    "Gill Sans MT",
    "Gill Sans MT Condensed",
    "Gill Sans MT Ext Condensed Bold",
    "Gill Sans Ultra Bold",
    "Gill Sans Ultra Bold Condensed",
    "Gloucester MT Extra Condensed",
    "Goudy Old Style",
    "Goudy Stout",
    "Haettenschweiler",
    "Harlow Solid Italic",
    "HarmonyOS Sans SC",
    "Harrington",
    "High Tower Text",
    "Impact",
    "Imprint MT Shadow",
    "Informal Roman",
    "Ink Free",
    "Javanese Text",
    "Jokerman",
    "Juice ITC",
    "Karmatic Arcade",
    "Kristen ITC",
    "Kunstler Script",
    "Lato",
    "Lato Light",
    "Lato Semibold",
    "Leelawadee UI",
    "Leelawadee UI Semilight",
    "Lucida Bright",
    "Lucida Calligraphy",
    "Lucida Console",
    "Lucida Fax",
    "Lucida Handwriting",
    "Lucida Sans",
    "Lucida Sans Typewriter",
    "Lucida Sans Unicode",
    "MS Gothic",
    "MS Outlook",
    "MS PGothic",
    "MS Reference Sans Serif",
    "MS Reference Specialty",
    "MS Sans Serif",
    "MS Serif",
    "MS UI Gothic",
    "MT Extra",
    "MV Boli",
    "Magneto",
    "Maiandra GD",
    "Malgun Gothic",
    "Malgun Gothic Semilight",
    "Marlett",
    "Matura MT Script Capitals",
    "Microsoft Himalaya",
    "Microsoft JhengHei",
    "Microsoft JhengHei Light",
    "Microsoft JhengHei UI",
    "Microsoft JhengHei UI Light",
    "Microsoft New Tai Lue",
    "Microsoft PhagsPa",
    "Microsoft Sans Serif",
    "Microsoft Tai Le",
    "Microsoft YaHei",
    "Microsoft YaHei Light",
    "Microsoft YaHei UI",
    "Microsoft YaHei UI Light",
    "Microsoft Yi Baiti",
    "MingLiU-ExtB",
    "MingLiU_HKSCS-ExtB",
    "MingLiU_MSCS-ExtB",
    "Mistral",
    "Modern",
    "Modern No. 20",
    "Mongolian Baiti",
    "Monotype Corsiva",
    "Myanmar Text",
    "NSimSun",
    "NanumGothic",
    "Niagara Engraved",
    "Niagara Solid",
    "Nirmala Text",
    "Nirmala Text Semilight",
    "Nirmala UI",
    "Nirmala UI Semilight",
    "Noto Sans JP",
    "OCR A Extended",
    "Old English Text MT",
    "Onyx",
    "PMingLiU-ExtB",
    "Palace Script MT",
    "Palatino Linotype",
    "Papyrus",
    "Parchment",
    "Perpetua",
    "Perpetua Titling MT",
    "Playbill",
    "Poor Richard",
    "Pristina",
    "ROG Fonts",
    "ROG Fonts STRIX SCAR",
    "ROG Fonts v1.6",
    "Rage Italic",
    "Ravie",
    "Roboto",
    "Rockwell",
    "Rockwell Condensed",
    "Rockwell Extra Bold",
    "Roman",
    "Sans Serif Collection",
    "Script",
    "Script MT Bold",
    "Segoe Fluent Icons",
    "Segoe MDL2 Assets",
    "Segoe Print",
    "Segoe Script",
    "Segoe UI",
    "Segoe UI Black",
    "Segoe UI Emoji",
    "Segoe UI Historic",
    "Segoe UI Light",
    "Segoe UI Semibold",
    "Segoe UI Semilight",
    "Segoe UI Symbol",
    "Segoe UI Variable Display",
    "Segoe UI Variable Display Light",
    "Segoe UI Variable Display Semib",
    "Segoe UI Variable Display Semil",
    "Segoe UI Variable Small",
    "Segoe UI Variable Small Light",
    "Segoe UI Variable Small Semibol",
    "Segoe UI Variable Small Semilig",
    "Segoe UI Variable Text",
    "Segoe UI Variable Text Light",
    "Segoe UI Variable Text Semibold",
    "Segoe UI Variable Text Semiligh",
    "Shaka Pow",
    "Showcard Gothic",
    "SimSun",
    "SimSun-ExtB",
    "SimSun-ExtG",
    "Sitka Banner",
    "Sitka Banner Semibold",
    "Sitka Display",
    "Sitka Display Semibold",
    "Sitka Heading",
    "Sitka Heading Semibold",
    "Sitka Small",
    "Sitka Small Semibold",
    "Sitka Subheading",
    "Sitka Subheading Semibold",
    "Sitka Text",
    "Sitka Text Semibold",
    "Small Fonts",
    "Snap ITC",
    "Source Han Sans JP",
    "Source Han Sans JP Normal",
    "Stencil",
    "Sylfaen",
    "Symbol",
    "System",
    "Tahoma",
    "Tempus Sans ITC",
    "Terminal",
    "Times New Roman",
    "Times New Roman Baltic",
    "Times New Roman CE",
    "Times New Roman CYR",
    "Times New Roman Greek",
    "Times New Roman TUR",
    "Trebuchet MS",
    "Tw Cen MT",
    "Tw Cen MT Condensed",
    "Tw Cen MT Condensed Extra Bold",
    "Verdana",
    "Viner Hand ITC",
    "Vivaldi",
    "Vladimir Script",
    "Webdings",
    "Wide Latin",
    "Wingdings",
    "Wingdings 2",
    "Wingdings 3",
    "Xolonium",
    "Yu Gothic",
    "Yu Gothic Light",
    "Yu Gothic Medium",
    "Yu Gothic UI",
    "Yu Gothic UI Light",
    "Yu Gothic UI Semibold",
    "Yu Gothic UI Semilight",
]

TEXT_MAP: Dict[str, str] = {
    # Boutons principaux
    "📁 Dossier": "btn_folder",
    "🖼️ Images": "btn_images",
    "🚀 Traiter tout": "process_all",
    "✅ Traiter sélection": "process_sel",
    "👁️ Preview": "preview_btn",
    "📂 Charger": "load",
    "✂️ Crop 128×32": "crop",
    "↶ Undo": "undo",
    "DMD Converter v2.0": "app_header",
    "🔄 Reset": "reset",
    "💾 Exporter GIF": "export_gif",
    "📚 Multi-images": "multi_images",
    "🎬 Morphing": "morphing",
    "🎬 Générer": "generate_preview",
    "🎬 Prévisualiser": "preview_btn",
    "▶️ Preview": "preview_btn",
    "⏹️ Stop": "stop",
    "🗑️ Effacer": "clear",
    "💾 Exporter": "export",
    "🔄 Rafraîchir": "refresh",
    "🔒 Verrouiller": "lock",
    "🔒 Verrouiller pour le batch": "lock_batch",
    "🔓 Réautoriser sélection": "reauthorize",
    "✓ Tout": "select_all",
    "✗ Rien": "select_none",
    "⇄ Inverser": "invert_sel",
    # Labels et sections
    "Source:": "source",
    "Images": "images",
    "Paramètres Globaux": "global_params",
    "FPS:": "fps",
    "Durée (s):": "duration",
    "Vitesse scroll:": "scroll_speed",
    "Contraste:": "contrast",
    "Saturation:": "saturation",
    "Couleurs GIF:": "gif_colors",
    "Informations Image": "image_info",
    "Image Originale": "original_image",
    "Aperçu DMD Principal (128x32)": "dmd_preview",
    "Propositions IA": "ia_proposals",
    "Effets Temps Réel": "realtime_effects",
    "Luminosité:": "brightness",
    "Netteté:": "sharpness",
    "Filtres": "filters",
    "Outils Dessin": "draw_tools",
    "Couleur": "color",
    "Tolérance:": "tolerance",
    "Édition": "edition",
    "Aperçu Animation DMD": "anim_preview",
    "Animation:": "animation",
    "Direction:": "direction",
    "Vitesse:": "speed",
    "Boucle:": "loop",
    "Répétitions:": "repetitions",
    "Texte": "text",
    "Police": "font",
    "Famille:": "family",
    "Taille:": "size",
    "Gras": "bold",
    "Italique": "italic",
    "Couleur texte": "text_color",
    "Couleur fond": "bg_color",
    "Effets Texte": "text_effects",
    "Effet:": "effect",
    "Effet couleur:": "color_effect",
    "Type:": "type",
    "Apparence": "appearance",
    "Thème:": "theme",
    "🌙 Sombre": "dark",
    "☀️ Clair": "light",
    "Langue:": "language",
    "Comportement": "behavior",
    "Ajouter type d'animation au nom de fichier": "add_anim_name",
    "Forcer pixel-perfect": "pixel_perfect",
    "Quitter": "quit",
    "⛔ Interrompre": "stop",
    "↶ Annuler": "undo",
    "Auto-ajuster": "auto_adjust",
    "Aperçu Animation": "preview_animation",
    "Entrez du texte et générez": "enter_text_generate",
    "ℹ️ Informations Image": "info_image",
    "Export": "export",
    "Qualité par défaut:": "default_quality",
    "Performance": "performance",
    "Activer cache IA": "enable_cache",
    "🗑️ Vider cache": "clear_cache",
    "Logs": "logs",
    "Sauvegarder logs automatiquement": "auto_save_logs",
    "📄 Exporter logs": "export_logs",
    "🗑️ Effacer logs": "clear_logs",
    "Auto-scroll": "autoscroll",
    "Filtrer:": "filter",
    "Prêt": "ready",
    "Récursif": "recursive",
    "Fond noir": "black_bg",
    "Images chargées (morphing)": "loaded_images",
    "Votre texte ici...": "your_text_here",
    # Filtres
    "Flou": "blur",
    "Flou Gaussien": "gaussian_blur",
    "Contours": "edges",
    "Relief": "emboss",
    "Détails+": "detail",
    "Inverser": "invert",
    "Miroir H": "mirror_h",
    "Miroir V": "mirror_v",
    "Rotation 90°": "rotate_90",
    "N&B": "grayscale",
    "Posteriser": "posterize",
    "Solariser": "solarize",
    "Égaliser": "equalize",
    "Auto-contraste": "autocontrast",
    # Animations
    "Scroll": "scroll",
    "Fondu entrant": "fade_in",
    "Fondu sortant": "fade_out",
    "Zoom avant": "zoom_in",
    "Zoom arrière": "zoom_out",
    "Rotation": "rotate",
    "Vague": "wave",
    "Rebond": "bounce",
    "Flash": "flash",
    "Glisser gauche": "slide_left",
    "Glisser droite": "slide_right",
    "Glisser haut": "slide_top",
    "Glisser bas": "slide_bottom",
    "Spirale": "spiral",
    "Tremblement": "shake",
    "Pulsation": "pulse",
    "Glitch": "glitch",
    "Pixelisation": "pixelate",
    "Transition floue": "blur_transition",
    "Décalage couleur": "color_shift",
    # Directions
    "Auto": "auto",
    "Horizontal": "horizontal",
    "Vertical": "vertical",
    "Statique": "static",
    # Boucles
    "Normal": "normal",
    "Ping-pong": "ping_pong",
    "Infini": "infinite",
    # Outils dessin
    "🎨 Remplissage": "fill",
    "🧹 Gomme Magique": "eraser",
    # Contrôles avancés
    "Contrôles Avancés": "advanced_controls",
    "Easing:": "easing",
    "Opacité:": "opacity",
    "Linéaire": "linear",
    "Ease In": "ease_in",
    "Ease Out": "ease_out",
    "Ease In-Out": "ease_in_out",
    "Délai début (s):": "delay_start",
    "Inverser direction": "reverse_direction",
    "Rebond aux bords": "bounce_edges",
    "Animations & Paramètres": "animations_params",
}
